### ISSUE TITLE
Add 'namespace: kube-system' to ServiceAccount resource in node.yaml

### ISSUE THREAD

**Issue by ghost** [giantswarm/kube-stresscheck#7]
Environment:
- Windows 10 Pro
- Minikube v1.9.0
- Kubernetes client & server versions v1.18.0
- `kubectl apply -f https://raw.githubusercontent.com/giantswarm/kube-stresscheck/master/examples/node.yaml`

Command run:
`kubectl describe rs kube-stresscheck-7f75dbbcb7 -n kube-system`

Output:
`Warning  FailedCreate  2m45s (x17 over 8m13s)  replicaset-controller  Error creating: pods "kube-stresscheck-7f75dbbcb7-" is forbidden: error looking up service account kube-system/kube-stresscheck: serviceaccount "kube-stresscheck" not found.`

After adding the namespace to the ServiceAccount, everything ran smoothly.

**Comment by aprofessionalusername** [comment]
Specifically patch the yaml
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-stresscheck
```
Turns into

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-stresscheck
  namespace: kube-system
```
