### ISSUE TITLE
examples/cluster.yaml DaemonSet and PSP YAML Spec not compatible with newer K8s API Version

### ISSUE THREAD

**Issue by biswarup1290dass** [giantswarm/kube-stresscheck#9]
The below attached YAML is tested on k8s 1.21 with minor fixes on PSP and DaemonSet YAML Spec & deprecated API versions

Also fixes similar issue - https://github.com/giantswarm/kube-stresscheck/issues/7 (add namespace to serviceAccount resource) but for cluster.yaml

~Unable to raise PR due to restricted repository permissions.~

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-stresscheck-psp
rules:
  - apiGroups:
    - extensions
    resources:
    - podsecuritypolicies
    verbs:
    - use
    resourceNames:
    - kube-stresscheck-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-stresscheck-psp
subjects:
  - kind: ServiceAccount
    name: kube-stresscheck
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-stresscheck-psp
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-stresscheck
  namespace: kube-system
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kube-stresscheck-psp
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - 'secret'
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-stresscheck
  namespace: kube-system
  labels:
    app: kube-stresscheck
spec:
  selector:
    matchLabels:
      app: kube-stresscheck
  template:
    metadata:
      labels:
        app: kube-stresscheck
    spec:
      serviceAccount: kube-stresscheck
      securityContext:
        runAsUser: 0
      containers:
      - name: kube-stresscheck
        image: quay.io/giantswarm/kube-stresscheck:latest
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
```
